name: example-python
on:
  workflow_dispatch: {}
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.5.0
      with:
        python-version: 3.11
    - name: run test
      run: python -m unittest test_add.py
